all:
  hosts:
    master:
      ansible_host: 192.168.3.243
      ip: 192.168.3.243
      access_ip: 192.168.3.243
    # node1:
    #   ansible_host: 192.168.1.10
    #   ip: 192.168.1.10
    #   access_ip: 192.168.1.10
    # node2:
    #   ansible_host: 192.168.1.11
    #   ip: 192.168.1.11
    #   access_ip: 192.168.1.11
  children:
    kube_control_plane:
      hosts:
        master:
    kube_node:
      hosts:
        master:
        # node1:
        # node2:
    etcd:
      hosts:
        master:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    flannel_rr:
      hosts: {}
